### ISSUE TITLE
[Feature Request] Do not purge named entities.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Wicked7000/EntityPurger#2]
The feature could be listed in the config as
"purgeNamedEntities": false 

I may go ahead and do this myself as I would like to add this to my modpack so people don't have to restart their server/game for mobs to spawn again.

**Comment by SlayerTheChikken** [comment]
I finished with the codez, I would request a merge but I removed FTB integrations and changed the config so here are the commits instead:
https://github.com/Slayer5934/EntityPurger/commit/4433118c6b6bdf64c40909dacb52aad20ce103a1
https://github.com/Slayer5934/EntityPurger/commit/110d35824338be4222d8687c22105d52ec6ad6dd

**Comment by Wicked7000** [comment]
Is there a reason you want to remove FTB Integration? (would probably be better to have a toggle in the config)

**Comment by Wicked7000** [comment]
I've added both features you'd require to the main mod in version 1.2.4 please see the below updated wiki for information.
(Wiki here: https://github.com/Wicked7000/EntityPurger/wiki/EntityPurger-1.2.4)

**Comment by SlayerTheChikken** [comment]
> Is there a reason you want to remove FTB Integration? (would probably be better to have a toggle in the config)

The reason is I had no idea how to drop in the dependencies so I can build in eclipse :P

**Comment by SlayerTheChikken** [comment]
> I've added both features you'd require to the main mod in version 1.2.4 please see the below updated wiki for information. (Wiki here: https://github.com/Wicked7000/EntityPurger/wiki/EntityPurger-1.2.4)

Woooo thank you, I can also close my fork if you would like

**Comment by Wicked7000** [comment]
@Slayer5934 If you are want to make your own custom version feel free (just credit me somewhere in the readme or link back here), otherwise you can probably just close it
